//using HarmonyLib;
//using RimWorld;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Reflection;
//using System.Text;
//using System.Threading.Tasks;
//using Verse;

//namespace Helpers.Patching
//{
//    [HarmonyPatch]
//    public static class Patch_SurgeryOutcomeComp_RecipeSuccessChance
//    {
//        static MethodBase TargetMethod()
//        {
//            //RimWorld.SurgeryOutcomeComp_RecipeSuccessChance
//            // Locate the nested class and method generated by the compiler
//            var nestedType = typeof(SurgeryOutcomeComp_RecipeSuccessChance);
//            return nestedType?.GetMethod("AffectQuality", BindingFlags.Instance | BindingFlags.Public);

//        }

//        public static void Prefix(RecipeDef recipe, Pawn surgeon, Pawn patient, List<Thing> ingredients, BodyPartRecord part, Bill bill, ref float quality, object __instance)
//        {
            

//            DebugHelpers.DebugLog("Patch_SurgeryOutcomeComp_RecipeSuccessChance", $"Patch_SurgeryOutcomeComp_RecipeSuccessChance" +
//                $" has susceffly Been added to the Postfix");

//        }
//    }
//}
