using HarmonyLib;
using RimWorld;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using Verse;
using Verse.AI;

namespace Helpers
{
    [HarmonyPatch]
    public static class Patch_PostToilsRecipe
    {
        static MethodBase TargetMethod()
        {
            // Locate the nested class and method generated by the compiler
            var nestedType = typeof(Toils_Recipe).GetNestedType("<>c__DisplayClass2_0", BindingFlags.NonPublic);
            return nestedType?.GetMethod("<DoRecipeWork>b__1", BindingFlags.Instance | BindingFlags.NonPublic);
        }

        public static void Postfix(object __instance)
        {

            // Inspect closure fields
            var fields = __instance.GetType().GetFields(BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            DebugHelpers.DebugLog("Patch_PostToilsRecipe", $"Closure fields: {string.Join(", ", fields.Select(f => f.Name))}");

            // Try retrieving the Toil field
            var toilField = __instance.GetType().GetField("toil", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public);
            if (toilField == null)
            {
                Log.Warning("Failed to retrieve 'toil' field from closure.");
                return;
            }

            var toil = toilField.GetValue(__instance) as Toil;
            if (toil == null)
            {
                Log.Warning("Failed to cast 'toil' to Toil.");
                return;
            }

            DebugHelpers.DebugLog("Patch_PostToilsRecipe", $"Toil retrieved: {toil}");

            // Get the actor (main pawn performing the job)
            Pawn actor = toil?.GetType().GetField("actor", BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public)?.GetValue(toil) as Pawn;
            if (actor == null)
            {
                Log.Warning("Helpers: Unable to retrieve Pawn 'actor'.");
                return;
            }

            // Retrieve the current job and job driver
            var curJob = actor.jobs?.curJob;
            var jobDriver = actor.jobs?.curDriver as JobDriver_DoBill;
            if (curJob == null || jobDriver == null)
            {
                Log.Warning("Postfix: Failed to retrieve current job or job driver.");
                return;
            }

            // Get the helper component
            var helperComp = actor.GetHelperComponent();
            if (helperComp == null || !helperComp.IsBeingHelped)
            {
                // No helpers active, nothing to adjust
                return;
            }

            // Adjust workLeft using the helper contribution
            float helperContribution = HelperMechanics.CalculateHelperContribution(
                actor,
                jobDriver,
                curJob.RecipeDef,
                helperComp.CurrentHelpers,
                curJob.RecipeDef.workSpeedStat
            );

            jobDriver.workLeft -= helperContribution;

            DebugHelpers.DebugLog("Patch_PostToilsRecipe", $" Adjusted workLeft by {helperContribution}. Remaining work: {jobDriver.workLeft}");

            // Log experience updates handled within HelperMechanics (if applicable)
            foreach (var helper in helperComp.CurrentHelpers)
            {
                DebugHelpers.DebugLog("Patch_PostToilsRecipe", ": {helper.Name} assisted {actor.Name} and contributed.");
            }
        }
    }
}

